soramitsu/fearless-iOS

- .swiftlint.yml
- fearless.xcodeproj/project.pbxproj
- fearless.xcodeproj/xcshareddata/xcschemes/fearless.xcscheme
- fearless/Common/Extension/Foundation/Decimal+Kusama.swift
- fearless/Common/Network/JSONRPC/RuntimeDispatchInfo.swift
- fearless/Common/Network/JSONRPC/RuntimeVersion.swift
- fearless/Common/Network/JSONRPC/WebSocketEngine.swift
- fearless/Common/Scale/ScaleCoding.swift
- fearless/Common/Scale/Types/AccountInfo.swift
- fearless/Common/Scale/Types/Era.swift
- fearless/Common/Scale/Types/Extrinsic.swift
- fearless/Common/Scale/Types/TransferCall.swift
- fearlessIntegrationTests/JSONRPCTests.swift
- fearlessTests/Scale/ScaleExtrinsicTests.swift
- add model for extrinsic
- add integration tests to check support for Westend network
> Westend support

- fearless.xcodeproj/project.pbxproj
- fearless/Common/Extension/SettingsExtension.swift
- fearless/Common/ViewController/NavigationController/FearlessNavigationBar.swift
- fearless/Common/ViewController/NavigationController/FearlessNavigationController.swift
- fearless/Modules/AccountConfirm/AccountConfirmInteractor.swift
- fearless/Modules/AccountImport/AccountImportInteractor.swift
- fearless/Modules/AccountImport/AccountImportViewFactory.swift
- fearless/Modules/Root/RootInteractor.swift
- fearless/Modules/Root/RootPresenter.swift
- fearless/Modules/Root/RootProtocol.swift
- fearless/Modules/Root/RootWireframe.swift
- fearlessTests/Mocks/ModuleMocks.swift
- fearlessTests/Modules/AccountConfirm/AccountConfirmTests.swift
- fearlessTests/Modules/AccountCreate/AccountCreateTests.swift
- fearlessTests/Modules/AccountImport/AccountImportTests.swift
- fearlessTests/Modules/Root/RootTests.swift
- add mnemonic confirmation flag to startup logic
- add tests
> FLW-123 Implement startup logic

- fearless/Modules/Profile/ProfileView/ProfileDetailsTableViewCell.xib
- fearless/Modules/Profile/ProfileView/ProfileSectionTableViewCell.swift
- fearless/Modules/Profile/ProfileView/ProfileSectionTableViewCell.xib
- fearless/Modules/Profile/ProfileViewController.swift
- fix spacing between items on profile screen
> Profile view design

- fearless/Modules/AccountManagement/AccountManagementViewController.swift
- remove whole section when all items removed from it
> Fix remove account

- fearless/Common/Model/Language.swift
- fearless/Common/ViewController/SelectionListViewController/SelectionListViewController.xib
- fearless/Common/ViewController/SelectionListViewController/View/SelectionSubtitleTableViewCell.xib
- fearless/Common/ViewController/SelectionListViewController/View/SelectionTitleTableViewCell.xib
- fearless/Modules/LanguageSelection/LanguageSelectionPresenter.swift
- fearless/ba-RU.lproj/Localizable.strings
- fearless/en.lproj/Localizable.strings
- fearless/es-CO.lproj/Localizable.strings
- fearless/fr.lproj/Localizable.strings
- fearless/it.lproj/Localizable.strings
- fearless/ja.lproj/Localizable.strings
- fearless/ru.lproj/Localizable.strings
- fearless/uk.lproj/Localizable.strings
> FLW-159 View with language selection

- Podfile
- Podfile.lock
- fearless/Modules/AccountImport/AccountImportViewController.swift
- fearless/Modules/AccountImport/AccountImportViewController.xib
- fearless/Modules/AccountInfo/AccountInfoViewController.swift
- fearless/Modules/AccountInfo/AccountInfoViewController.xib
- fearless/Modules/UsernameSetup/UsernameSetupViewController.swift
- fearless/Modules/UsernameSetup/UsernameSetupViewController.xib
- add google like animation for text fields: username create, import and account info
> FLW-254 Implement google-like input field

- fearless.xcodeproj/project.pbxproj
- fearless/Common/Extension/UIKit/TriangularedView+Style.swift
- fearless/Modules/AccountImport/AccountImportViewController.swift
- fearless/Modules/AccountInfo/AccountInfoViewController.xib
- fearless/Modules/NetworkInfo/NetworkInfoInteractor.swift
- fearless/Modules/NetworkInfo/NetworkInfoPresenter.swift
- fearless/Modules/NetworkInfo/NetworkInfoProtocols.swift
- fearless/Modules/NetworkInfo/NetworkInfoViewController.swift
- fearless/Modules/NetworkInfo/NetworkInfoViewController.xib
- fearless/Modules/NetworkInfo/NetworkInfoViewFactory.swift
- fearless/Modules/NetworkInfo/NetworkInfoWireframe.swift
- fearless/Modules/NetworkManagement/NetworkManagementPresenter.swift
- fearless/Modules/NetworkManagement/NetworkManagementProtocols.swift
- fearless/Modules/NetworkManagement/NetworkManagementViewFactory.swift
- fearless/Modules/NetworkManagement/NetworkManagementWireframe.swift
- fearless/ba-RU.lproj/Localizable.strings
- fearless/en.lproj/Localizable.strings
- fearless/es-CO.lproj/Localizable.strings
- fearless/fr.lproj/Localizable.strings
- fearless/it.lproj/Localizable.strings
- fearless/ja.lproj/Localizable.strings
- fearless/ru.lproj/Localizable.strings
- fearless/uk.lproj/Localizable.strings
- fearlessTests/Mocks/ModuleMocks.swift
- fearlessTests/Modules/NetworkInfo/NetworkInfoTests.swift
> FLW-260 View details of connection

- fearless/Common/Model/ManagedConnectionItem.swift
- fearless/Common/Network/JSONRPC/JSONRPCOperation.swift
- fearless/Modules/ModifyConnection/Error/ModifyConnectionError.swift
- fearless/Modules/ModifyConnection/ModifyConnectionViewController.swift
- fearless/Modules/NetworkManagement/NetworkManagementInteractor.swift
- fearless/Modules/NetworkManagement/NetworkManagementPresenter.swift
- fearless/Modules/NetworkManagement/NetworkManagementProtocols.swift
- fearlessTests/Mocks/ModuleMocks.swift
- move/remove custom connections
> FLW-259 Edit connections

- fearless/Common/Extension/Model/NetworkType+ViewModel.swift
- fearless/Common/Network/JSONRPC/WebSocketEngine.swift
- fearless/Common/Network/WalletNetworkOperationFactory.swift
- fearless/Modules/Wallet/Transfer/TransferContext.swift
- fearless/Modules/Wallet/WalletContextFactory.swift
- replace request for genesis hash with static one
> Fix genesis hash

- Podfile
- Podfile.lock
- fearless.xcodeproj/project.pbxproj
- fearless/Common/Helpers/Scheduler.swift
- fearless/Common/Network/JSONRPC/JSONRPCEngine.swift
- fearless/Common/Network/JSONRPC/JSONRPCInfo.swift
- fearless/Common/Network/JSONRPC/JSONRPCOperation.swift
- fearless/Common/Network/JSONRPC/ReconnectionStrategy.swift
- fearless/Common/Network/JSONRPC/WebSocketEngine.swift
- fearless/Common/Network/SubstrateOperationFactory.swift
- fearless/Common/Network/WalletNetworkOperationFactory+Protocol.swift
- fearless/Common/Network/WalletNetworkOperationFactory.swift
- fearless/Common/Reachability/ReachabilityManager.swift
- fearless/Common/Services/ApplicationService.swift
- fearless/Common/Services/WebSocketService/WebSocketEngineFactory.swift
- fearless/Common/Services/WebSocketService/WebSocketService.swift
- fearless/Common/Services/WebSocketService/WebSocketServiceProtocol.swift
- fearless/Modules/MainTabBar/MainTabBarInteractor.swift
- fearless/Modules/MainTabBar/MainTabBarViewFactory.swift
- fearless/Modules/Wallet/WalletContextFactory.swift
- fearlessIntegrationTests/JSONRPCTests.swift
- fearlessTests/Helper/SchedulerTests.swift
- fearlessTests/Mocks/CommonMocks.swift
- custom web sockets engine add with reconnection strategy
- reconnection is trigged by the timer, new request arriving or connection reachability change
- web sockets request uses single engine
> FLW-384 Updates for WebSockets lifecycle

- fearless.xcodeproj/project.pbxproj
- fearless/AppDelegate.swift
- fearless/Common/Extension/UIKit/UIFont+Style.swift
- fearless/Common/Network/JSONRPC/WebSocketEngine.swift
- fearless/Common/Protocols/StatusPresentable.swift
- fearless/Common/Services/WebSocketService/WebSocketService.swift
- fearless/Common/View/ApplicationStatusView/ApplicationStatusView.swift
- fearless/Common/View/FearlessWindow.swift
- fearless/Modules/MainTabBar/MainTabBarViewFactory.swift
- fearless/Modules/NetworkAvailabilityLayer/NetworkAvailabilityLayerPresenter.swift
- fearless/Modules/NetworkAvailabilityLayer/NetworkAvailabilityLayerProtocols.swift
- fearless/ba-RU.lproj/Localizable.strings
- fearless/en.lproj/Localizable.strings
- fearless/es-CO.lproj/Localizable.strings
- fearless/fr.lproj/Localizable.strings
- fearless/it.lproj/Localizable.strings
- fearless/ja.lproj/Localizable.strings
- fearless/ru.lproj/Localizable.strings
- fearless/uk.lproj/Localizable.strings
- display connection problem when there is more than 1 consecutive attempts to reconnect
> FLW-380: Network status bar

- fearless.xcodeproj/project.pbxproj
- fearless/Common/Model/ExportOption.swift
- fearless/Common/Operation/AccountOperationFactory.swift
- fearless/Modules/AccountInfo/AccountInfoInteractor.swift
- fearless/Modules/AccountInfo/AccountInfoPresenter.swift
- fearless/Modules/AccountInfo/AccountInfoProtocols.swift
- fearless/Modules/AccountInfo/AccountInfoViewFactory.swift
- fearless/Modules/AccountInfo/AccountInfoWireframe.swift
- fearlessTests/Mocks/ModuleMocks.swift
- fearlessTests/Modules/AccountInfo/AccountInfoExportTests.swift
- fearlessTests/Modules/AccountInfo/AccountInfoTests.swift
- add opportunity to choose export source type with auth
> FLW-418 View for Source type

- fearless.xcodeproj/project.pbxproj
- fearless/Common/Network/JSONRPC/Health.swift
- fearless/Common/Network/JSONRPC/RPCMethod.swift
- fearless/Common/Network/JSONRPC/WebSocketEngine+Delegate.swift
- fearless/Common/Network/JSONRPC/WebSocketEngine.swift
- fearlessIntegrationTests/JSONRPCTests.swift
- add 30s socket ping to prevent connection drop
> FLW-429 Add ping in WebSockets each 30s

- fearless.xcodeproj/project.pbxproj
- fearless/Common/Protocols/ModalAlertPresenting.swift
- fearless/Common/ViewController/NavigationController/FearlessNavigationController.swift
- fearless/Modules/Export/ExportMnemonicConfirm/ExportMnemonicConfirmWireframe.swift
- fearless/Modules/Pincode/ChangePincode/PinChangeInteractor.swift
- fearless/Modules/Pincode/ChangePincode/PinChangeWireframe.swift
- fearless/Modules/Pincode/PinSetup/PinSetupInteractor.swift
- fearless/Modules/Pincode/PinSetup/PinSetupProtocol.swift
- fearless/Modules/Pincode/PinSetup/PinSetupViewController.swift
- fearless/Modules/Pincode/PinSetup/PinViewFactory.swift
- fearless/Modules/Pincode/PinSetup/en.lproj/PinSetupViewController.xib
- fearless/Modules/Profile/ProfileWireframe.swift
- fearless/ba-RU.lproj/Localizable.strings
- fearless/en.lproj/Localizable.strings
- fearless/es-CO.lproj/Localizable.strings
- fearless/fr.lproj/Localizable.strings
- fearless/it.lproj/Localizable.strings
- fearless/ja.lproj/Localizable.strings
- fearless/ru.lproj/Localizable.strings
- fearless/uk.lproj/Localizable.strings
- fearlessTests/Mocks/ModuleMocks.swift
- fearlessTests/Modules/NetworkInfo/NetworkInfoTests.swift
- fearlessTests/Modules/Pincode/PincodeSetupTests.swift
- pincode change logic add
- fix duplicate access request for Face ID
> FLW-90 iOS: Change pin-code

- fearless.xcodeproj/project.pbxproj
- fearless/Common/Extension/ByteLengthProcessor+Username.swift
- fearless/Common/Helpers/ByteLengthProcessor.swift
- fearless/Modules/AccountImport/AccountImportPresenter.swift
- fearless/Modules/AccountInfo/AccountInfoPresenter.swift
- fearless/Modules/UsernameSetup/UsernameSetupPresenter.swift
- fearlessTests/Common/Helpers/ByteLengthEncodingTests.swift
- username must be 32 byte long (Create Account, Import Account, Account Info)
> FLW-280 iOS. Create account - not have boundary in "Choose name" field

- fearless/Common/Configs/ApplicationConfigs.swift
- fearless/Common/Helpers/MainTransitionHelper.swift
- fearless/Modules/AccountManagement/AccountManagementWireframe.swift
- fearless/Modules/AddAccount/Wireframes/AddConfirmationWireframe.swift
- fearless/Modules/AddAccount/Wireframes/AddImportedWireframe.swift
- fearless/Modules/ConnectionSelectAddingAccount/Wireframes/ConnectionAccountConfirmWireframe.swift
- fearless/Modules/ConnectionSelectAddingAccount/Wireframes/ConnectionAccountImportWireframe.swift
- fearless/Modules/LanguageSelection/LanguageSelectionWireframe.swift
- fearless/Modules/NetworkManagement/NetworkManagementWireframe.swift
- fearless/Modules/Pincode/PinSetup/en.lproj/PinSetupViewController.xib
- fix links for term and conditions and privacy policy
- fix navigation on import from 3rd party files
- fix pincode buttons highlighting
> fix links and misc

- README.md
TestFlight link -> AppStore link
> AppStore link update

- fearless/Configs/fearless.dev.xcconfig
- name of the app for dev env must be Fearless Dev
> fix name for dev build

- Jenkinsfile
- Podfile
- Podfile.lock
- fearless.xcodeproj/project.pbxproj
- fearless/Common/Crypto/ExtrinsicFactoryProtocol.swift
- fearless/Common/Crypto/ExtrinsicFactoryV27.swift
- fearless/Common/Extension/FearlessUtils/StorageKeyFactory+Implicit.swift
- fearless/Common/Extension/FearlessUtils/StorageUpdateData+Decoding.swift
- fearless/Common/Extension/Storage/ChainStorage+Decodable.swift
- fearless/Common/Extension/Wallet/TransactionHistoryItem+Extrinsic.swift
- fearless/Common/Network/JSONRPC/RPCMethod.swift
- fearless/Common/Network/WalletNetworkFacade+Storage.swift
- fearless/Common/Network/WalletNetworkOperationFactory+Protocol.swift
- fearless/Common/Network/WalletNetworkOperationFactory.swift
- fearless/Common/Scale/Types/AccountInfo.swift
- fearless/Common/Scale/Types/BaseExtrinsic.swift
- fearless/Common/Scale/Types/ExtrinsicPayload.swift
- fearless/Common/Scale/Types/ExtrinsicV27.swift
- fearless/Common/Scale/Types/Multiaddress.swift
- fearless/Common/Scale/Types/TransferCallV27.swift
- fearless/Common/Services/WebSocketService/StorageSubscription/ActiveEraSubscription.swift
- fearless/Common/Services/WebSocketService/StorageSubscription/BaseStorageChildSubscription.swift
- fearless/Common/Services/WebSocketService/StorageSubscription/TransferSubscription.swift
- fearless/Common/Services/WebSocketService/StorageSubscription/UpgradeV28Subscription.swift
- fearless/Common/Services/WebSocketService/WebSocketSubscriptionFactory.swift
- fearless/Modules/Wallet/AccountDetails/View/AssetDetailsViewModelFactory.swift
- fearless/Modules/Wallet/WalletContextFactory.swift
- fearlessIntegrationTests/JSONRPCTests.swift
- fearlessTests/Common/Scale/ScaleExtrinsicTests.swift
- add subscription to UpdateDualRefCount
- parse and create transactions based on UpdateDualRefCount
> Fix v28 runtime upgrade

- fearless.xcodeproj/project.pbxproj
- fearless/Common/Extension/Model/Chain+Info.swift
- fearless/Common/Network/JSONRPC/JSONRPCAliases.swift
- fearless/Common/Protocols/SharingPresentable.swift
- fearless/Common/Reachability/ReachabilityManager.swift
- fearless/Common/Services/WebSocketService/StorageSubscription/RuntimeVersionSubscription.swift
- fearless/Common/Services/WebSocketService/StorageSubscription/StakingInfoSubscription.swift
- fearless/Common/Services/WebSocketService/StorageSubscription/StorageSubscriptionContainer.swift
- fearless/Common/View/ActionView/BorderedSubtitleActionView+Inspectable.swift
- fearless/Common/View/ActionView/ExpandableActionControl+Inspectable.swift
- fearless/Common/View/DetailsTriangularedView+Inspectable.swift
- fearless/Common/View/TriangularedView/TriangularedBlurButton+Inspectable.swift
- fearless/Common/View/TriangularedView/TriangularedButton+Inspectable.swift
- fearless/Common/ViewController/ModalPicker/ModalPickerViewController.swift
- fix warnings appeared after migration to new swiftlint version
> swiftlint migration to 0.42.0

- fearless.xcodeproj/project.pbxproj
- fearless/Common/DataProvider/SingleValueProviderFactory.swift
- fearless/Common/Services/ExtrinsicService/ExtrinsicService.swift
- fearless/Common/Substrate/Types/BaseExtrinsic.swift
- fearless/Common/View/TriangularedView/TriangularedBlurView.swift
- fearless/Modules/Staking/SelectedValidators/SelectedValidatorsWireframe.swift
- fearless/Modules/Staking/StakingAmount/StakingAmountPresenter.swift
- fearless/Modules/Staking/StakingAmount/StakingAmountViewController.xib
- fearless/Modules/Staking/StakingMain/StakingMainInteractor.swift
- fearless/Modules/Staking/StakingMain/StakingMainPresenter.swift
- fearless/Modules/Staking/StakingMain/StakingMainProtocols.swift
- fearless/Modules/Staking/StakingMain/StakingMainViewController.swift
- fearless/Modules/Staking/StakingMain/StakingMainViewController.xib
- fearless/Modules/Staking/StakingMain/StakingMainViewFactory.swift
- fearless/Modules/Staking/StakingMain/StakingMainWireframe.swift
- fearless/Modules/Staking/StakingMain/ViewModel/RewardViewModel.swift
- fearless/Modules/Staking/StakingMain/ViewModel/RewardViewModelFactory.swift
- fearless/Modules/Staking/StakingMain/ViewModel/StakingViewModelFacade.swift
- fearlessTests/Mocks/DataProviders/RewardCalculatorServiceStub.swift
- fearlessTests/Mocks/DataProviders/SingleValueProviderFactoryStub.swift
- fearlessTests/Mocks/ModuleMocks.swift
- fearlessTests/Modules/Staking/StakingMain/StakingMainTests.swift
Implement staking reward widget on main staking screen
> FLW-580 Widget Estimate your earnings

- fearless.xcodeproj/project.pbxproj
- fearless/Common/Extension/Foundation/BigInt+Hex.swift
- fearless/Common/Services/WebSocketService/StorageSubscription/TransferSubscription.swift
- fearless/Modules/Wallet/Receive/AccountShareFactory.swift
- fearless/Modules/Wallet/Receive/ReceiveAccountViewModel.swift
- fearless/Modules/Wallet/Receive/ReceiveConfigurator.swift
- fearless/Modules/Wallet/Receive/View/ReceiveViewFactory.swift
- fearless/Modules/Wallet/WalletContextFactory.swift
- fixed bug when username not updating on the receive screen
- improve blocknumber hex parsing via BigUInt instead of Data
> Recent set of bug fixes

- fearless.xcodeproj/project.pbxproj
- fearless.xcodeproj/xcshareddata/xcbaselines/8438E1CE24BFAAD2001BDB13.xcbaseline/0CBA0634-E260-422A-A54D-0326AA5D9BBC.plist
- fearless.xcodeproj/xcshareddata/xcbaselines/8438E1CE24BFAAD2001BDB13.xcbaseline/24255ADB-1167-4055-A89C-15D155BEDA4F.plist
- fearless.xcodeproj/xcshareddata/xcbaselines/8438E1CE24BFAAD2001BDB13.xcbaseline/Info.plist
- fearless/Common/Services/EraValidatorsService/EraValidatorService+Fetch.swift
- fearless/Common/Services/EraValidatorsService/EraValidatorService.swift
- fearless/Common/Services/RewardCalculatorService/RewardCalculatorService.swift
- fearless/Common/Services/RuntimeRegistryService/RuntimeRegistryService.swift
- fearlessIntegrationTests/CalculatorServiceTests.swift
- add benchmarks for era validator service
- improve performance of reward calculator fetch request
> Benchmark era validator service

- fearless.xcodeproj/project.pbxproj
- fearless/Modules/Staking/StakingMain/StakingMainViewController.swift
- fearless/Modules/Staking/StakingMain/View/RewardEstimationView.xib
- fearless/Modules/Staking/StakingMain/View/ValidationView.swift
- fearless/Modules/Staking/StakingMain/View/ValidationView.xib
- fearless/ba-RU.lproj/Localizable.strings
- fearless/en.lproj/Localizable.strings
- fearless/es-CO.lproj/Localizable.strings
- fearless/fr.lproj/Localizable.strings
- fearless/it.lproj/Localizable.strings
- fearless/ja.lproj/Localizable.strings
- fearless/ru.lproj/Localizable.strings
- fearless/uk.lproj/Localizable.strings
- add view to display validator state
> FLW-611 iOS: Validator account Staking tab state

- fearless.xcodeproj/project.pbxproj
- fearless/Common/Services/WebSocketService/StorageSubscription/BaseStorageChildSubscription.swift
- fearless/Common/Services/WebSocketService/StorageSubscription/TransferSubscription.swift
- fearless/Modules/Staking/StakingMain/StakingMainPresenter.swift
- fearless/Modules/Staking/StakingMain/StakingMainProtocols.swift
- fearless/Modules/Staking/StakingMain/StakingMainViewController.swift
- fearless/Modules/Staking/StakingMain/StateMachine/States/NominatorState+Status.swift
- fearless/Modules/Staking/StakingMain/ViewModel/StakingStateViewModelFactory.swift
- fearlessTests/Mocks/ModuleMocks.swift
- add alerts to display information for each nominator status
- make transaction processing non-blocking
> FLW-641 Stake widget

- fearless.xcodeproj/project.pbxproj
- fearless/Modules/Staking/StakingPayoutConfirmation/StakingPayoutConfirmationInteractor.swift
- fearless/Modules/Staking/StakingPayoutConfirmation/StakingPayoutConfirmationPresenter.swift
- fearless/Modules/Staking/StakingPayoutConfirmation/StakingPayoutConfirmationProtocols.swift
- fearless/Modules/Staking/StakingPayoutConfirmation/StakingPayoutConfirmationViewController.swift
- fearless/Modules/Staking/StakingPayoutConfirmation/StakingPayoutConfirmationViewFactory.swift
- fearless/Modules/Staking/StakingPayoutConfirmation/StakingPayoutConfirmationViewLayout.swift
- fearless/Modules/Staking/StakingPayoutConfirmation/StakingPayoutConfirmationWireframe.swift
- fearless/Modules/Staking/StakingRewardDetails/StakingRewardDetailsPresenter.swift
- fearless/Modules/Staking/StakingRewardDetails/StakingRewardDetailsProtocols.swift
- fearless/Modules/Staking/StakingRewardDetails/StakingRewardDetailsViewController.swift
- fearless/Modules/Staking/StakingRewardDetails/StakingRewardDetailsViewFactory.swift
- fearless/Modules/Staking/StakingRewardDetails/StakingRewardDetailsWireframe.swift
- fearless/Modules/Staking/StakingRewardDetails/View/RewardDetailsRow.swift
- fearless/Modules/Staking/StakingRewardPayouts/StakingRewardPayoutsPresenter.swift
- fearless/Modules/Staking/StakingRewardPayouts/StakingRewardPayoutsProtocols.swift
- fearless/Modules/Staking/StakingRewardPayouts/StakingRewardPayoutsViewController.swift
- fearlessTests/Modules/StakingPayoutConfirmation/StakingPayoutConfirmationTests.swift
> FLW-677 Implement "Payout confirmation" layout

- Podfile
- Podfile.lock
- fearless.xcodeproj/project.pbxproj
- fearless/Common/View/TriangularedView/TriangularedView.swift
- fearless/Modules/Pincode/PinSetup/PinSetupViewController.swift
- fearless/Modules/Staking/StakingMain/StakingMainViewController.swift
- fearless/Modules/Staking/StakingMain/StakingMainViewController.xib
- fearless/Modules/Staking/StakingMain/View/NetworkInfoView.swift
- fearless/Modules/Staking/StakingMain/View/NetworkInfoView.xib
- fearless/Modules/Staking/StakingMain/View/RewardEstimationView.xib
- moved layout to separate view
- fix expansion animation
- fix touch area of the header
> Network info view improvements

- fearless.xcodeproj/project.pbxproj
- fearless/Assets.xcassets/colorSkeletonEnd.colorset/Contents.json
- fearless/Assets.xcassets/colorSkeletonStart.colorset/Contents.json
- fearless/Common/Protocols/SkeletonLoadable.swift
- fearless/Modules/Staking/StakingMain/StakingMainPresenter.swift
- fearless/Modules/Staking/StakingMain/StakingMainProtocols.swift
- fearless/Modules/Staking/StakingMain/StakingMainViewController.swift
- fearless/Modules/Staking/StakingMain/View/NetworkInfoView.swift
- fearless/Modules/Staking/StakingMain/View/NetworkInfoView.xib
- fearless/Modules/Staking/StakingMain/View/RewardEstimationView.swift
- fearless/Modules/Staking/StakingMain/View/RewardEstimationView.xib
- fearless/Modules/Staking/StakingMain/ViewModel/NetworkInfoViewModelFactory.swift
- fearless/Modules/Staking/StakingMain/ViewModel/StakingEstimationViewModel.swift
- fearless/Modules/Staking/StakingMain/ViewModel/StakingStateViewModelFactory.swift
- fearless/Modules/Staking/StakingMain/ViewModel/StakingViewState.swift
- fearlessTests/Mocks/ModuleMocks.swift
- add loading state on network info widget
- add loading state on estimate reward widget
> FLW-637 Shimmering animation (loading state)

- Podfile
- Podfile.lock
- fearless/Common/Services/EraValidatorsService/EraValidatorService+Fetch.swift
- update fearless utils
- optimise validators storage
> Decoding and db optimizations

- fearless/Resources/runtime-default.json
- fearless/Resources/runtime-kusama.json
- fearless/Resources/runtime-polkadot.json
- fearless/Resources/runtime-westend.json
- update default json needed for dynamic runtime decoding
> Update default types

- fearless.xcodeproj/project.pbxproj
- fearless/Common/DataProvider/Sources/SubscanRewardSource.swift
- fearless/Common/Extension/Int+Operations.swift
- fearless/Common/Extension/Wallet/AssetTransactionData+HistoryItemData.swift
- fearless/Common/Model/TransactionType.swift
- fearless/Common/Network/Subscan/Data/ExtrinsicIndexWrapper.swift
- fearless/Common/Network/Subscan/Data/SubscanExtrinsicData.swift
- fearless/Common/Network/Subscan/Data/SubscanTransferData.swift
- fearless/Common/Network/Subscan/Info/RewardInfo.swift
- fearless/Common/Network/Subscan/SubscanDefinitions.swift
- fearless/Common/Network/Subscan/SubscanOperationFactory.swift
- fearless/Common/Network/WalletNetworkFacade+Protocol.swift
- fearless/Common/Network/WalletRemoteHistoryItemProtocol.swift
- fearless/Common/Network/WalletRemoteHistoryOperationFactory.swift
- fearless/Modules/Wallet/History/TransactionHistoryContext.swift
- fearless/Modules/Wallet/History/View/HistoryItemTableViewCell.swift
- fearlessTests/Common/DataProvider/RewardDataSourceTests.swift
- add extrinsics source
- implement merge logic
> Remote history fetch

- Podfile
- Podfile.lock
- fearless.xcodeproj/project.pbxproj
- fearless/Common/Extension/Foundation/String+Substrate.swift
- fearless/Common/Network/WalletNetworkFacade+Protocol.swift
- fearless/Common/Network/WalletNetworkFacade+TxHistory.swift
- fearless/Modules/Wallet/History/View/HistoryItemTableViewCell.swift
- fearless/Modules/Wallet/History/ViewModel/TransactionHistoryViewModelFactory.swift
- fearless/Modules/Wallet/History/WalletHistoryStyle.swift
- fearless/Modules/Wallet/HistoryFilter/WalletHistoryFilterViewFactory.swift
- fearless/Modules/Wallet/HistoryFilter/WalletHistoryFilterWireframe.swift
- fearless/Modules/Wallet/TransactionDetails/TransactionDetailsViewModelFactory+Extrinsic.swift
- fearless/ba-RU.lproj/Localizable.strings
- fearless/en.lproj/Localizable.strings
- fearless/es-CO.lproj/Localizable.strings
- fearless/fr.lproj/Localizable.strings
- fearless/it.lproj/Localizable.strings
- fearless/ja.lproj/Localizable.strings
- fearless/ru.lproj/Localizable.strings
- fearless/uk.lproj/Localizable.strings
- fearlessTests/Mocks/WalletCommandFactoryProtocolMock.swift
- fix loading indicator style
- show loading indicator when history request  in progress
- format call/module name
- update title label style depending on tx type
> Transaction history improvements

- Podfile
- Podfile.lock
- fearless.xcodeproj/project.pbxproj
- fearless/Common/DataProvider/SingleValueProviderFactory.swift
- fearless/Common/DataProvider/Sources/ElectionStatusSource.swift
- fearless/Common/Extension/FearlessUtils/RuntimeMetadata+Internal.swift
- fearless/Common/Extension/FearlessUtils/StorageKeyFactory+Implicit.swift
- fearless/Common/Model/Chain.swift
- fearless/Common/Services/WebSocketService/StorageSubscription/ElectionStatusSubscription.swift
- fearless/Common/Services/WebSocketService/StorageSubscription/TransferSubscription.swift
- fearless/Common/Services/WebSocketService/WebSocketSubscriptionFactory.swift
- fearless/Common/Substrate/Types/CallCodingPath.swift
- fearless/Common/Substrate/Types/ElectionPhase.swift
- fearless/Common/Substrate/Types/ElectionStatus.swift
- fearless/Common/Substrate/Types/StorageCodingPath.swift
- fearlessTests/Mocks/ModuleMocks.swift
- subscribe to Staking.ElectionStatus if available otherwise try to subscribe to ElectionProviderMultiPhase.CurrentPhase
> Fix election status

- fearless/Modules/Staking/StakingRewardDetails/StakingRewardDetailsPresenter.swift
- fearless/Modules/Staking/StakingRewardDetails/StakingRewardDetailsViewFactory.swift
> FLW-734 Reward details: show validator icon

- fearless/Modules/Staking/StakingRewardPayouts/StakingRewardPayoutsPresenter.swift
- fearless/Modules/Staking/StakingRewardPayouts/StakingRewardPayoutsProtocols.swift
- fearless/Modules/Staking/StakingRewardPayouts/StakingRewardPayoutsViewController.swift
- fearless/Modules/Staking/StakingRewardPayouts/View/StakingRewardPayoutsViewLayout.swift
> FLW-733 Payouts list: Implement EmptyStateView & LoadableView

- fearless.xcodeproj/project.pbxproj
- fearless/Modules/Staking/StakingRewardPayouts/StakingRewardPayoutsPresenter.swift
- fearless/Modules/Staking/StakingRewardPayouts/StakingRewardPayoutsProtocols.swift
- fearless/Modules/Staking/StakingRewardPayouts/StakingRewardPayoutsViewController.swift
- fearless/Modules/Staking/StakingRewardPayouts/StakingRewardPayoutsViewFactory.swift
- fearless/Modules/Staking/StakingRewardPayouts/ViewModel/StakingPayoutViewModelFactory.swift
In next PR I'll implement localization for Payouts list
> FLW-733 Payouts list: implement viewModel factory

- fearless/Modules/Staking/StakingRewardDetails/View/StakingRewardDetailsBaseTableCell.swift
- fearless/Modules/Staking/StakingRewardPayouts/View/StakingRewardHistoryTableCell.swift
- Add "Payout rewards" cell selection color
- Remove cell selection at "Reward details"
> FLW-733 Payouts: fix ui defects

- fearless/Common/Services/WebSocketService/StorageSubscription/StakingAccountSubscription.swift
- add subscription to stash/controller balance after resolution to display when action performed from the account
> FLW-797: Subscription to Controller balance

- fearless.xcodeproj/project.pbxproj
- fearless/Common/Extension/FearlessUtils/RuntimeMetadata+Internal.swift
- fearless/Common/Extension/Storage/CDTransactionHistoryItem+CoreDataDecodable.swift
- fearless/Common/Extension/Wallet/AssetTransactionData+HistoryItemData.swift
- fearless/Common/Extension/Wallet/TransactionHistoryItem+Extrinsic.swift
- fearless/Common/Extension/Wallet/TransactionHistoryItem+Wallet.swift
- fearless/Common/Model/TransactionHistoryItem.swift
- fearless/Common/Network/JSONRPC/JSONRPCAliases.swift
- fearless/Common/Network/JSONRPC/StorageQuery.swift
- fearless/Common/Operation/StorageRequestFactory.swift
- fearless/Common/Services/WebSocketService/StorageSubscription/AccountInfoSubscription.swift
- fearless/Common/Services/WebSocketService/StorageSubscription/ExtrinsicProcessing.swift
- fearless/Common/Services/WebSocketService/StorageSubscription/TransactionSubscription.swift
- fearless/Common/Services/WebSocketService/StorageSubscription/TransferSubscription.swift
- fearless/Common/Services/WebSocketService/WebSocketSubscriptionFactory.swift
- fearless/Common/Storage/SubstrateDataModel.xcdatamodeld/SubstrateDataModel.xcdatamodel/contents
- fearless/Common/Substrate/Types/BalanceDepositEvent.swift
- fearless/Common/Substrate/Types/EventCodingPath.swift
- fearless/Common/Substrate/Types/EventRecord.swift
- fearless/Common/Substrate/Types/StorageCodingPath.swift
- fearlessTests/Common/Services/ExtrinsicProcessingTests.swift
- fearlessTests/Mocks/DataProviders/RuntimeCodingServiceStub.swift
- add extrinsic processing and status determination based on events
- calculate extrinsic fee based on events
> FLW-622: Runtime Events support for improving finality status fetch

- Podfile
- Podfile.lock
- fearless/Common/Helpers/AmountFormatterFactory.swift
- fearless/Common/ViewController/ModalPicker/ModalInfoFactory.swift
- fearless/Modules/Staking/StakingAmount/ViewModel/BalanceViewModelFactory.swift
- fearless/Modules/Staking/StakingAmount/ViewModel/RewardDestinationViewModelFactory.swift
- fearless/Modules/Staking/StakingMain/View/NetworkInfoView.xib
- fearless/Modules/Staking/StakingMain/ViewModel/RewardViewModelFactory.swift
- fearless/Modules/Wallet/AccountDetails/View/AssetDetailsViewModelFactory.swift
- fearless/Modules/Wallet/AccountList/ViewModel/WalletAssetViewModelFactory.swift
- fearless/Modules/Wallet/Commands/ExistentialDepositInfoCommand.swift
- fearless/Modules/Wallet/Commands/WalletAccountInfoCommand.swift
- fearless/Modules/Wallet/History/ViewModel/TransactionHistoryViewModelFactory.swift
- fearless/Modules/Wallet/TransactionDetails/TransactionDetailsViewModelFactory+Transfer.swift
- fearless/Modules/Wallet/TransactionDetails/TransactionDetailsViewModelFactory.swift
- fearless/Modules/Wallet/Transfer/TransferViewModelFactory.swift
- fearless/Modules/Wallet/TransferConfirm/TransferConfirmViewModelFactory.swift
- add data formatter to support very small numbers and very big numbers
> FLW-783 Format numbers

- fearless.xcodeproj/project.pbxproj
- fearless/Modules/Staking/ControllerAccount/ControllerAccountPresenter.swift
- fearless/Modules/Staking/ControllerAccount/ControllerAccountProtocols.swift
- fearless/Modules/Staking/ControllerAccount/ControllerAccountWireframe.swift
- fearless/Modules/Staking/ControllerAccountConfirmation/ControllerAccountConfirmationInteractor.swift
- fearless/Modules/Staking/ControllerAccountConfirmation/ControllerAccountConfirmationPresenter.swift
- fearless/Modules/Staking/ControllerAccountConfirmation/ControllerAccountConfirmationProtocols.swift
- fearless/Modules/Staking/ControllerAccountConfirmation/ControllerAccountConfirmationViewController.swift
- fearless/Modules/Staking/ControllerAccountConfirmation/ControllerAccountConfirmationViewFactory.swift
- fearless/Modules/Staking/ControllerAccountConfirmation/ControllerAccountConfirmationWireframe.swift
- fearless/Modules/Staking/ControllerAccountConfirmation/View/ControllerAccountConfirmationLayout.swift
- fearless/Modules/Staking/ControllerAccountConfirmation/ViewModel/ControllerAccountConfirmationVM.swift
- fearlessTests/Mocks/ModuleMocks.swift
- fearlessTests/Modules/ControllerAccount/ControllerAccountTests.swift
- fearlessTests/Modules/ControllerAccountConfirmation/ControllerAccountConfirmationTests.swift
> FLW-790 "Change controller" confirmation

- fearless.xcodeproj/project.pbxproj
- fearless/Modules/Staking/Model/StakingConstants.swift
- fearless/Modules/Staking/RecommendedValidators/RecommendationsComposing.swift
- fearless/Modules/Staking/RecommendedValidators/RecommendedValidatorsPresenter.swift
- fearless/Modules/Staking/RecommendedValidators/RecommendedValidatorsViewController.swift
- fearless/Modules/Staking/RecommendedValidators/RecommendedValidatorsViewController.xib
- fearless/Modules/Staking/RecommendedValidators/RecommendedValidatorsViewFactory.swift
- fearless/ba-RU.lproj/Localizable.strings
- fearless/en.lproj/Localizable.strings
- fearless/es-CO.lproj/Localizable.strings
- fearless/fr.lproj/Localizable.strings
- fearless/it.lproj/Localizable.strings
- fearless/ja.lproj/Localizable.strings
- fearless/ru.lproj/Localizable.strings
- fearless/uk.lproj/Localizable.strings
- fearlessTests/Modules/Staking/RecommendedValidators/RecommendationsComposerTests.swift
- fearlessTests/Modules/Staking/RecommendedValidators/RecommendedValidatorsTests.swift
- limit up to 2 validators from the single cluster in recommendations
> FLW-818 iOS: Recommended Validators: Add only up to 2 nodes from 1 cluster

- fearless/Modules/Staking/Stories/Model/StoriesFactory.swift
- fearless/Resources/runtime-default.json
- fearless/Resources/runtime-kusama.json
- fearless/Resources/runtime-polkadot.json
- fearless/Resources/runtime-westend.json
- update runtime jsons
- update stories
> FLW-822 Update strings: Stories & Subscan API

- fearless/Modules/Staking/ControllerAccount/ControllerAccountViewController.swift
- fearless/Modules/Staking/ControllerAccount/View/ControllerAccountViewLayout.swift
- fearless/Modules/Staking/ControllerAccount/ViewModel/ControllerAccountViewModel.swift
- fearless/Modules/Staking/ControllerAccount/ViewModel/ControllerAccountViewModelFactory.swift
- fearless/en.lproj/Localizable.strings
- fearlessTests/Mocks/ModuleMocks.swift
> FLW-827 Update "Controller account" layout. Add hints

- fearless/Common/Helpers/AmountFormatterFactory.swift
- fearless/Modules/Staking/ControllerAccount/ViewModel/ControllerAccountViewModelFactory.swift
- fearless/Modules/Staking/Stories/Model/StoriesFactory.swift
- fix case when stash equal to controller in set controller flow
- fix precision
- fix stories titles
> Minor fixes

- Podfile
- Podfile.lock
- Rambafile
- generamba-module.sh
- switch generamba template to support viper with "in code" layout
- update fearless utils version
> Libraries update

- Podfile
- Podfile.lock
- fearless/Modules/Wallet/TransactionDetails/TransactionDetailsViewModelFactory+Transfer.swift
- fearless/Modules/Wallet/TransactionDetails/TransactionDetailsViewModelFactory.swift
- fix empty state top insets on [contacts screen](https://github.com/soramitsu/Capital-iOS/pull/112)
- include fee for outgoing transfers
> FLW-833 iOS. Fix Empty state on input field in Contacts

- fearless.xcodeproj/project.pbxproj
- fearless/Common/Crypto/WalletPrimitiveFactory.swift
- fearless/Common/Extension/Model/Chain+Info.swift
- fearless/Common/Extension/Model/Chain+ViewModel.swift
- fearless/Common/Extension/Model/ConnectionItem+Default.swift
- fearless/Common/Extension/Model/SNAddressType+Chain.swift
- fearless/Common/Extension/Model/SNAddressType+ViewModel.swift
- fearless/Common/Extension/Model/WalletAssetId+Chain.swift
- fearless/Common/Extension/Model/WalletAssetId+Display.swift
- fearless/Common/Model/Chain.swift
- fearless/Common/Model/WalletAssetId.swift
- fearless/Common/Network/Subscan/SubscanDefinitions.swift
- fearless/Common/Network/WalletNetworkFacade+Protocol.swift
- fearless/Common/PurchaseProvider/RampProvider.swift
- fearless/Resources/runtime-rococo.json
- add rococo network. Note: we are using ```kusamaSecondary``` address type because our app doesn't support networks with the same address type for now
> add rococo network

- fearless/Modules/Staking/StakingMain/StakingMainInteractor+InputProtocol.swift
- fearless/Modules/Staking/StakingMain/StakingMainInterator+Subscription.swift
- fearless/Modules/Staking/StakingMain/StakingMainPresenter.swift
> FLW-870 Show "missing controller" error on Redeem alert action

- fearless/Modules/Staking/StakingMain/View/NominationView.xib
- fearless/Modules/Staking/StakingMain/View/ValidationView.xib
add staking widget tap zone for validator
> FLW-882 iOS. Staking widget. Incorrect tap zone for Staking for Validator

- fearless/Common/Extension/Foundation/NSPredicate+Filter.swift
- fearless/Common/Helpers/AccountRepositoryFactory.swift
- fearless/Modules/Staking/Protocols/StakingErrorPresentable.swift
- fearless/Modules/Staking/StakingMain/StakingMainInteractor+InputProtocol.swift
- fearless/Modules/Staking/StakingMain/StakingMainInteractor.swift
- fearless/Modules/Staking/StakingMain/StakingMainInterator+Subscription.swift
- fearless/Modules/Staking/StakingMain/StakingMainPresenter.swift
- fearless/Modules/Staking/StakingMain/StakingMainProtocols.swift
- fearless/Modules/Staking/StakingMain/StakingMainViewFactory.swift
- fearless/en.lproj/Localizable.strings
- fearlessTests/Mocks/CommonMocks.swift
- fearlessTests/Mocks/ModuleMocks.swift
- fearlessTests/Modules/Staking/StakingMain/StakingMainTests.swift
> FLW-870 Can't redeem if you haven't controller

- fearless/Common/Extension/UIKit/GradientButton+Style.swift
- fearless/Modules/Crowdloan/CustomCrowdloan/Bifrost/BifrostBonusService.swift
- fearless/Modules/Crowdloan/ReferralCrowdloan/ReferralCrowdloanPresenter.swift
- fearless/Modules/Crowdloan/ReferralCrowdloan/ReferralCrowdloanViewController.swift
- fearless/Modules/Crowdloan/ReferralCrowdloan/ReferralCrowdloanViewFactory.swift
- fearlessTests/Modules/Crowdloan/ReferralCrowdloan/ReferralCrowdloanTests.swift
- add remote validation of the Bifrost's referral codes
- fix localization on referral screen
- fix apply button style on referral screen
> FLW-970 iOS. Bifrost. No check for referral code.

- fearless/Common/Helpers/ChainDateCalculator.swift
- fearless/Modules/Crowdloan/CrowdloanContribution/CrowdloanContributionViewModelFactory.swift
- fearless/Modules/Crowdloan/CrowdloanList/ViewModel/CrowdloansViewModelFactory.swift
- display leasing period as difference between current date and last slot date
> FLW-973 iOS. Crowdloans. Fix leasing period

- Podfile
- Podfile.lock
- fearless/Modules/Crowdloan/CrowdloanList/CrowdloanListInteractor.swift
- fearless/Modules/Crowdloan/CrowdloanList/View/ActiveCrowdloanTableViewCell.swift
- fearless/Modules/Crowdloan/CrowdloanList/View/BaseCrowdloanTableViewCell.swift
- fearless/Modules/Crowdloan/CrowdloanList/View/CompletedCrowdloanTableViewCell.swift
- fearless/Modules/Crowdloan/CrowdloanList/ViewModel/CrowdloansViewModelFactory.swift
- add crowdloan sorting: by raised desc, by ned asc
- fix crowdloan list display on polkadot
- update fearless utils library
- fix cell selection in crowdloan list
> Crowdloan sorting

- fearless.xcodeproj/project.pbxproj
- fearless/Common/Substrate/Types/ParachainSlotLease.swift
- fearless/Common/Substrate/Types/StorageCodingPath.swift
- fearless/Modules/Crowdloan/CrowdloanList/CrowdloanListInteractor.swift
- fearless/Modules/Crowdloan/CrowdloanList/CrowdloanListPresenter.swift
- fearless/Modules/Crowdloan/CrowdloanList/CrowdloanListProtocols.swift
- fearless/Modules/Crowdloan/CrowdloanList/ViewModel/CrowdloansViewModelFactory.swift
- fearless/Modules/Crowdloan/Model/ParachainLeaseInfo.swift
- fearless/Modules/Crowdloan/Operation/CrowdloanOperationFactory.swift
- fearlessTests/Mocks/DataProviders/CrowdloansOperationFactoryStub.swift
- fearlessTests/Mocks/ModuleMocks.swift
- fearlessTests/Modules/Crowdloan/CrowdloanList/CrowdloanListTests.swift
- query slot.leases to find if parachain leased something
- mark parachain as completed (won auction) if there is fund leased by it
> FLW-1000 iOS: Add "Completed" crowdloans

- fearless/Modules/Crowdloan/CrowdloanList/CrowdloanListInteractor.swift
- fearless/Modules/Crowdloan/CrowdloanList/CrowdloanListPresenter.swift
- fearless/Modules/Crowdloan/CrowdloanList/CrowdloanListProtocols.swift
- fearless/Modules/Crowdloan/CrowdloanList/CrowdloanListViewController.swift
- fearless/Modules/Crowdloan/CrowdloanList/View/CompletedCrowdloanTableViewCell.swift
- fearlessTests/Mocks/ModuleMocks.swift
- fearlessTests/Modules/Crowdloan/CrowdloanList/CrowdloanListTests.swift
- refresh crowdlowns info on block changes
- show "you contributed" as white for all states
> Crowdloan bug fixes

- fearless/Modules/Staking/StakingBalance/StakingBalancePresenter.swift
- fearless/Modules/Staking/StakingBalance/StakingBalanceViewFactory.swift
- fearlessTests/Modules/Staking/StakingBalance/StakingBalanceTests.swift
- integrate validation runner into balance staking screen
- add validation for controller on rebond
> FLW-998 iOS. Staking balance. Add alert on Rebond "Add controller..." when without controller

- fearless/Modules/Staking/Model/StakingAlert.swift
- fearless/Modules/Staking/StakingMain/StakingMainViewController.swift
- fearless/Modules/Staking/StakingMain/View/AlertsView.swift
- fearless/Modules/Staking/StakingMain/ViewModel/StakingStateViewModelFactory+Alerts.swift
- fearless/en.lproj/Localizable.strings
> FLW-963 Update alerts widget & Waiting for next era

- Podfile.lock
- fearless/Common/Extension/Foundation/Charset+Mnemonic.swift
- fearless/Modules/AccountImport/Model/MnemonicTextNormalizer.swift
- fix mnemonic import to take into account newlines: FLW-1016
- fix screen dismissal when more than one in stack: FLW-1052
> Fix mnemonic and alerts

- fearless/Modules/Wallet/HistoryFilter/WalletHistoryFilterViewLayout.swift
> FLW-1057 Wallet. Filters. Fix "Show" title margin

- fearless/Modules/Staking/StakingRedeem/View/StakingRedeemLayout.swift
- fearless/Modules/Staking/StakingUnbondConfirm/View/StakingUnbondConfirmLayout.swift
> FLW-917 Redeem and Unbond Confirmation window: fix tooltip position

- fearless/Modules/Staking/StakingBalance/StakingBalancePresenter.swift
- fearless/Modules/Staking/StakingRewardPayouts/StakingRewardPayoutsInteractor.swift
- fearless/Modules/Staking/StakingRewardPayouts/StakingRewardPayoutsViewController.swift
Screencasting by QA Lev Patolya
https://user-images.githubusercontent.com/17689921/126984312-ce8cd3d5-8750-4009-8272-16dc3b10a6b2.mp4
> FLW-1106 Fix "0 days left" instead of "payout expired"

- fearless/Modules/Staking/StakingRedeem/StakingRedeemInteractor.swift
- fearless/Modules/Staking/StakingRedeem/StakingRedeemPresenter.swift
- fearless/Modules/Staking/StakingRedeem/StakingRedeemProtocols.swift
- fearless/Modules/Staking/StakingRedeem/View/StakingRedeemLayout.swift
- fearless/Modules/Staking/StakingRedeem/ViewModel/StakingRedeemViewModel.swift
- fearless/Modules/Staking/StakingRedeem/ViewModel/StakingRedeemViewModelFactory.swift
- fearlessTests/Mocks/ModuleMocks.swift
- remove reward destination logic from redeem flow
> FLW-1107 iOS: Fix redeem, after unstash

- fearless/Common/DataProvider/SingleValueProviderFactory.swift
- fearless/Common/Model/ChainHistoryRange.swift
- fearless/Common/Model/EraValidatorInfo.swift
- fearless/Common/Services/EraValidatorsService/EraValidatorService+Fetch.swift
- fearless/Common/Services/EraValidatorsService/EraValidatorService.swift
- fearless/Modules/Staking/Operations/EraCountdownOperationFactory/EraCountdown.swift
- fearless/Modules/Staking/Operations/EraCountdownOperationFactory/EraCountdownOperationFactory.swift
- fearless/Modules/Staking/Operations/ValidatorOperationFactory.swift
- fearless/Modules/Staking/StakingBalance/StakingBalancePresenter.swift
- fearless/Modules/Staking/StakingBalance/ViewModel/StakingBalanceViewModelFactory.swift
- fearless/Modules/Staking/StakingMain/StakingMainPresenter.swift
- fearless/Modules/Staking/StakingMain/StateMachine/States/BondedState+Status.swift
- fearless/Modules/Staking/StakingMain/StateMachine/States/NominatorState+Status.swift
- fearless/Modules/Staking/StakingMain/StateMachine/States/ValidatorState+Status.swift
- fearless/Modules/Staking/StakingMain/View/NominationView.swift
- fearless/Modules/Staking/StakingMain/ViewModel/NominationViewModel.swift
- fearless/Modules/Staking/StakingMain/ViewModel/StakingStateViewModelFactory+Alerts.swift
- fearless/Modules/Staking/StakingMain/ViewModel/StakingStateViewModelFactory.swift
- fearless/Modules/Staking/StakingRewardPayouts/StakingRewardPayoutsPresenter.swift
- fearless/Modules/Staking/StakingRewardPayouts/StakingRewardPayoutsViewController.swift
- fearless/Modules/Staking/StakingRewardPayouts/ViewModel/StakingPayoutViewModelFactory.swift
- fearlessIntegrationTests/EraCountdownOperationFactoryTests.swift
- fearlessTests/Helper/WestendStub.swift
- fearlessTests/Mocks/DataProviders/EraCountdownOperationFactoryStub.swift
- fearlessTests/Mocks/DataProviders/EraValidatorsServiceStub.swift
- fearlessTests/Mocks/DataProviders/SingleValueProviderFactoryStub.swift
- add option to calculate time till next current era set
- fix timer on main screen based on nomination set time
- improve timer for payouts calculating till current era = payout era + history depth + 1
> Timers improvements

- fearless.xcodeproj/project.pbxproj
- fearless/Common/Extension/UIKit/UIBarButtonItem+Style.swift
- fearless/Common/Migration/SelectedLanguageMigrator.swift
- fearless/Common/ViewController/NavigationController/ImportantFlowNavigationController.swift
- fearless/Modules/Root/RootPresenterFactory.swift
- fearless/Modules/Staking/Operations/ValidatorOperationFactory.swift
- fearless/Modules/Staking/SelectValidatorsFlow/CustomValidatorList/CustomValidatorListPresenter.swift
- fearless/Modules/Staking/SelectValidatorsFlow/RecommendedValidatorList/RecommendedValidatorListViewController.xib
- fearless/Modules/Staking/SelectValidatorsFlow/SelectValidatorsStart/SelectValidatorsStartPresenter.swift
- fearless/Modules/Staking/SelectValidatorsFlow/SelectedValidatorList/SelectedValidatorListViewController.swift
- fearless/Modules/Staking/SelectValidatorsFlow/SelectedValidatorList/View/SelectedValidatorListViewLayout.swift
- fearless/Modules/Staking/SelectValidatorsFlow/ValidatorListFilter/ValidatorListFilterViewController.swift
- fearless/Modules/Staking/SelectValidatorsFlow/ValidatorSearch/ValidatorSearchPresenter.swift
- fearless/Modules/Staking/SelectValidatorsFlow/ValidatorSearch/ValidatorSearchProtocols.swift
- fearless/Modules/Staking/SelectValidatorsFlow/YourValidatorList/YourValidatorListViewController.swift
- fearlessTests/Mocks/ModuleMocks.swift
- fix basket in custom validator flow
- add slashing fetch with wannabe validators
- fix ui bug on custom validator flow
- add languages migrator
> FLW-1111 iOS: Fix total validators counter

- Podfile
- Podfile.lock
- fearless.xcodeproj/project.pbxproj
- fearless/Common/EventCenter/EventVisitor.swift
- fearless/Common/EventCenter/Events/RuntimeCoderEvents.swift
- fearless/Common/EventCenter/Events/RuntimeSyncEvents.swift
- fearless/Common/Model/ChainRegistry/AssetModel.swift
- fearless/Common/Model/ChainRegistry/ChainModel.swift
- fearless/Common/Operation/OperationManagerFacade.swift
- fearless/Common/Services/ChainRegistry/ChainRegistryFactory.swift
- fearless/Common/Services/ChainRegistry/RuntimeFilesOperationFactory.swift
- fearless/Common/Services/ChainRegistry/RuntimeProviderPool/CommonTypesSyncService.swift
- fearless/Common/Services/ChainRegistry/RuntimeProviderPool/RuntimeProvider.swift
- fearless/Common/Services/ChainRegistry/RuntimeProviderPool/RuntimeProviderFactory.swift
- fearless/Common/Services/ChainRegistry/RuntimeProviderPool/RuntimeProviderPool.swift
- fearless/Common/Services/ChainRegistry/RuntimeProviderPool/RuntimeSnapshot.swift
- fearless/Common/Services/ChainRegistry/RuntimeProviderPool/RuntimeSnapshotOperationFactory.swift
- fearless/Common/Services/ChainRegistry/SpecVersionSubscription.swift
- fearless/Common/Services/ChainRegistry/SpecVersionSubscriptionFactory.swift
- fearless/Common/Services/ExtrinsicService/ExtrinsicOperationFactory.swift
- fearless/Common/Services/RuntimeRegistryService/RuntimeRegistryService.swift
- fearlessTests/Common/Services/ChainRegistry/CommonTypesSyncTests.swift
- fearlessTests/Common/Services/ChainRegistry/RuntimeProviderTests.swift
- fearlessTests/Helper/RuntimeHelper.swift
- fearlessTests/Mocks/CommonMocks.swift
- add common types sync logic
- add type registry build and update logic
> Runtime provider

- fearless/Modules/Staking/StakingRewardPayouts/View/StakingRewardHistoryTableCell.swift
add compression resistance priority to labels
> FLW-1082 iOS: Staking. Pending rewards, format amounts in the list

- fearless/Modules/Staking/SelectValidatorsFlow/SelectValidatorsStart/SelectValidatorsStartPresenter.swift
change max validators to network constant only
> FLW-1071 iOS: Change custom validators. Select validators. Change boundary to staking.Constants.MaxNominators

- fearless/Modules/Crowdloan/CrowdloanContribution/CrowdloanContributionViewModelFactory.swift
- fearless/Modules/Staking/SelectValidatorsFlow/SelectValidatorsConfirm/ChangeTargets/ChangeTargetConfirmInteractor.swift
- fearless/Modules/Staking/SelectValidatorsFlow/SelectValidatorsConfirm/InitiatedBonding/InitiatedBondingConfirmInteractor.swift
- fearless/Modules/Staking/SelectValidatorsFlow/SelectValidatorsConfirm/Model/SelectValidatorsConfirmationModel.swift
- fearless/Modules/Staking/SelectValidatorsFlow/SelectValidatorsConfirm/SelectValidatorsConfirmInteractorBase.swift
- fearless/Modules/Staking/SelectValidatorsFlow/SelectValidatorsConfirm/SelectValidatorsConfirmPresenter.swift
- fearless/Modules/Staking/SelectValidatorsFlow/SelectValidatorsConfirm/SelectValidatorsConfirmProtocols.swift
- fearless/Modules/Staking/StakingAmount/StakingAmountPresenter.swift
- fearless/Modules/Staking/StakingMain/StakingMainPresenter.swift
- fearless/Modules/Staking/StakingRewardPayouts/ViewModel/StakingPayoutViewModelFactory.swift
- fearless/Modules/Staking/Validation/StakingDataValidatorFactory.swift
- fearlessTests/Mocks/ModuleMocks.swift
- remove restriction on max number of nominators on validators change
> FLW-1220: iOS: Remove limitation of staking parameters (e.g. Validators) when maximum validators are reached

- fearless/Common/Services/RewardCalculatorService/RewardCalculatorEngine.swift
- filter validators with 100% commission before taking median
> fix median comission calculation

- fearless/Modules/Wallet/Transfer/TransferDefinitionFactory.swift
- fearless/Modules/Wallet/View/WalletCompoundDetailsView.swift
- fearless/Modules/Wallet/View/WalletFearlessDefinition.swift
Fix UI elements composition on Send Flow and Transaction Details screen
> FLW-1293: Fix transfer history UI

- fearless/Common/Model/ChainHistoryRange.swift
- fearless/Modules/Staking/Analytics/Validators/ViewModel/AnalyticsValidatorsViewModelFactory.swift
> FLW-1323 Fix crash when open the Analytics screen: arithmetic overflow

- fearless/Common/View/Chart/ChartData.swift
- fearless/Modules/Staking/Analytics/Common/AnalyticsViewState.swift
- fearless/Modules/Staking/Analytics/Common/Module/AnalyticsPresenterBaseProtocols.swift
- fearless/Modules/Staking/Analytics/Common/Module/AnalyticsRewardsViewModel.swift
- fearless/Modules/Staking/Analytics/Model/AnalyticsPeriod.swift
- fearless/Modules/Staking/Analytics/Rewards/ViewModel/AnalyticsRewardsItemView.swift
- fearless/Modules/Staking/Analytics/Rewards/ViewModel/AnalyticsSummaryRewardViewModel.swift
- fearless/Modules/Staking/Analytics/Validators/AnalyticsValidatorsViewController.swift
- fearless/Modules/Staking/Analytics/Validators/ViewModel/AnalyticsValidatorItemViewModel.swift
- fearless/Modules/Staking/Analytics/Validators/ViewModel/AnalyticsValidatorsViewModel.swift
- fearless/Modules/Staking/StakingRewardPayouts/ViewModel/StakingRewardHistoryViewModel.swift
https://user-images.githubusercontent.com/17689921/135812426-3336e5e2-5de5-4ac0-82d4-15f3d4e40c64.mov
> FLW-1327 Fix Analytics, Validators tab: pie chart is updated several times

- fearless/Common/View/EtheriumAddressForRewardView.swift
- fearless/Modules/Crowdloan/CrowdloanContributionSetup/CrowdloanContributionSetupViewController.swift
- fearless/Modules/Crowdloan/CrowdloanContributionSetup/CrowdloanContributionSetupViewLayout.swift
fixed a bug with moonbeam ethereum address field
> moonbeam flow keyboard hotfix

- fearless.xcodeproj/project.pbxproj
- fearless/Common/Extension/UIKit/GradientButton+Style.swift
- fearless/Common/View/UIFactory.swift
- fearless/Modules/Crowdloan/CrowdloanContribution/CrowdloanContributionViewModelFactory.swift
- fearless/Modules/Crowdloan/CrowdloanContributionConfirm/CrowdloanContributionConfirmViewLayout.swift
- fearless/Modules/Crowdloan/CrowdloanContributionConfirm/CustomFlows/MoonbeamContributionConfirmInteractor.swift
- fearless/Modules/Crowdloan/CrowdloanContributionSetup/CrowdloanContributionSetupWireframe.swift
- fearless/Modules/Crowdloan/CustomCrowdloan/Astar/AstarBonusService.swift
- fearless/Modules/Crowdloan/CustomCrowdloan/Bifrost/BifrostBonusService.swift
- fearless/Modules/Crowdloan/CustomCrowdloan/CrowdloanBonusServiceProtocol.swift
- fearless/Modules/Crowdloan/CustomCrowdloan/Karura/KaruraBonusService.swift
- fearless/Modules/Crowdloan/Model/CrowdloanFlow.swift
- fearless/Modules/Crowdloan/ReferralCrowdloan/CustomFlow/AstarReferralCrowdloanPresenter.swift
- fearless/Modules/Crowdloan/ReferralCrowdloan/ReferralCrowdloanPresenter.swift
- fearless/Modules/Crowdloan/ReferralCrowdloan/ReferralCrowdloanProtocols.swift
- fearless/Modules/Crowdloan/ReferralCrowdloan/ReferralCrowdloanViewController.swift
- fearless/Modules/Crowdloan/ReferralCrowdloan/ReferralCrowdloanViewFactory.swift
- fearless/Modules/Crowdloan/ReferralCrowdloan/ReferralCrowdloanViewLayout.swift
- fearless/Modules/Crowdloan/ReferralCrowdloan/ViewModel/AstarReferralCrowdloanViewModel.swift
- fearless/Modules/Crowdloan/ReferralCrowdloan/ViewModel/ReferralCrowdloanViewModelProtocol.swift
- fearless/Modules/Crowdloan/ReferralCrowdloan/ViewModel/ReferralCrowdloanViewState.swift
- fearlessTests/Mocks/Crowdloan/CrowdloanBonusServiceStub.swift
- fearlessTests/Mocks/ModuleMocks.swift
- fearlessTests/Modules/Crowdloan/ReferralCrowdloan/ReferralCrowdloanTests.swift
* astar flow added [test environment]
* astar flow almost ready (invalid referral issue)
* ethereum case checking
* astar flow ready
* Added unsupported case to ignore it (#429)
* Updated failing custom flows parsing
* terms url optional, astar flow added unsupported state
* code review fixes
* code review fixes #2
* Test fixes
* Jenkins fix
Co-authored-by: Alex Oakley <oakley@soramitsu.co.jp>
> Astar crowdloan -> master

- fearless/Modules/Crowdloan/CrowdloanList/CrowdloanListInteractor.swift
- fearless/Modules/Crowdloan/CrowdloanList/CrowdloanListViewFactory.swift
- fearlessTests/Modules/Crowdloan/CrowdloanList/CrowdloanListTests.swift
We need make same changes to other presenters sometime
> (FLW-1390) presenter force unwrap removed

- fearless/Modules/Crowdloan/CrowdloanList/CrowdloanListInteractor.swift
disable add_memo history request
> disable add_memo history call

- Jenkinsfile
Signed-off-by: Ahmed Elkashef <ahmedelkashef2012@gmail.com>
> use mac-ios-1 agent

- fearless/Modules/AccountImport/AccountImportPresenter.swift
- fearless/Modules/AccountImport/AccountImportProtocols.swift
- fearless/Modules/AccountImport/AccountImportViewController.swift
- fearless/Modules/AccountImport/AccountImportViewLayout.swift
- fearless/Modules/UsernameSetup/UsernameSetupViewController.swift
hide username for replace chain flow, hide derivation path for ethereum seed
> (flw 1768) replace chain UI fix

- Jenkinsfile
[DevOps] Prepare Telegram bot to announce deployment to various project with notes
##Description.
Prepare Telegram bot to announce deployment to various project with notes.
Announces should include:
Name of the project (Firebase)
App version
Notes: features, bugs, issues completed and included to a build
Signed-off-by: Bao Tran [btran@soramitsu.co.jp](mailto:btran@soramitsu.co.jp)
> [FLW-1735] [DevOps] Prepare Telegram bot to announce deployment to various project with notes

- fearless/Common/Protocols/LoadableViewProtocol.swift
- fearless/Modules/StakingPool/StakingPoolInfo/StakingPoolInfoViewController.swift
[bug] [iOS] Nothing is active on the "pool info" screen of staking while the loader is showing and loading is in progress
> loading userinteraction fix

- Jenkinsfile
[FLW-3696]: automation flow GitHub jira 
1. Added new variable for Jenkins library function
Signed-off-by: Aleksey Kazakov <kazakov@soramitsu.co.jp>
[FLW-3696]: https://soramitsu.atlassian.net/browse/FLW-3696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FLW-3696]: automation flow GitHub jira

- Jenkinsfile
[DOPS-2962]: upload fearless iOS app to nexus
[DOPS-2962]: https://soramitsu.atlassian.net/browse/DOPS-2962?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOPS-2962]: upload fearless iOS app to nexus
